
export const REMOVE_CARD = 'REMOVE_CARD'
export const ADD_CARD = 'ADD_CARD'
export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
export const REQUEST_CARD = 'REQUEST_CARD'
export const RECEIVE_CARD = 'RECEIVE_CARD'
export const REQUEST_CARD_PLAYS = 'REQUEST_CARD_PLAYS'
export const RECEIVE_CARD_PLAYS = 'RECEIVE_CARD_PLAYS'
